// Pure push/fold logic — no DOM. Shared by the drill grader and the chart grids
// so they can never disagree. Tunable thresholds live here; ranking data is in
// charts.js (generated by tools/equity.py). Testable under Node (see tools/test_poker.js).
(function (g) {
  'use strict';

  // FALLBACK push/fold tables (used only if nash.js isn't loaded). When window.NASH
  // is present — generated by tools/solve/pushfold.js (approximate-Nash, BB-ante
  // pot) — jam/call grading uses solved per-hand EVs instead of these.
  var JAM = {
    EP: { 8: 0.28, 12: 0.22, 15: 0.18, 20: 0.14 },
    MP: { 8: 0.32, 12: 0.25, 15: 0.22, 20: 0.18 },
    CO: { 8: 0.37, 12: 0.32, 15: 0.28, 20: 0.23 },
    BTN: { 8: 0.48, 12: 0.39, 15: 0.35, 20: 0.34 },
    SB: { 8: 0.77, 12: 0.67, 15: 0.62, 20: 0.53 }
  };
  var CALL = {
    late: { 8: 0.54, 12: 0.37, 15: 0.32, 20: 0.25 },
    early: { 8: 0.29, 12: 0.17, 15: 0.13, 20: 0.09 }
  };
  var NASH_DEPTHS = [8, 10, 12, 15, 20];
  var EV_MARGIN = 0.15;                              // |EV| below this = genuine mix
  function nash() { return (typeof window !== 'undefined' ? window.NASH : g.NASH) || null; }
  function nearestDepth(stack) {
    var best = NASH_DEPTHS[0];
    NASH_DEPTHS.forEach(function (d) { if (Math.abs(d - stack) < Math.abs(best - stack)) best = d; });
    return best;
  }
  var STACKS = [8, 10, 12, 15, 20];

  // ±band (combo-weighted percentile) around a threshold where BOTH actions are fine
  // — the solver mixes here, so the drill shouldn't mark either answer wrong.
  var MARGIN = 0.035;

  // ---- Pocket Card action model: depths 10/20/30bb (short / medium / deep) ----
  // First-in OPEN range (jam at 10bb, raise at 20/30) — top fraction by your position.
  var OPEN = {
    10: { EP: 0.231, MP: 0.285, CO: 0.336, BTN: 0.433, SB: 0.71 },  // Nash-solved jam %s (25k-trial matrix)
    20: { EP: 0.15, MP: 0.20, CO: 0.28, BTN: 0.45, SB: 0.46 },
    30: { EP: 0.15, MP: 0.19, CO: 0.27, BTN: 0.46, SB: 0.42 },
    50: { EP: 0.16, MP: 0.20, CO: 0.27, BTN: 0.46, SB: 0.40 },
    100: { EP: 0.17, MP: 0.21, CO: 0.28, BTN: 0.48, SB: 0.38 }
  };
  // Facing ONE open, folded to you. tb = 3-bet (jam at 10/20, raise at 30); up to
  // call = flat. Wider vs a later opener. Approximate, linear (merged) guide.
  var VS = {
    10: { EP: { tb: 0.06, call: 0.08 }, MP: { tb: 0.07, call: 0.10 }, CO: { tb: 0.09, call: 0.13 }, BTN: { tb: 0.12, call: 0.17 } },
    20: { EP: { tb: 0.07, call: 0.10 }, MP: { tb: 0.08, call: 0.13 }, CO: { tb: 0.11, call: 0.18 }, BTN: { tb: 0.15, call: 0.24 } },
    30: { EP: { tb: 0.05, call: 0.13 }, MP: { tb: 0.06, call: 0.17 }, CO: { tb: 0.08, call: 0.24 }, BTN: { tb: 0.10, call: 0.33 } },
    50: { EP: { tb: 0.045, call: 0.14 }, MP: { tb: 0.055, call: 0.18 }, CO: { tb: 0.07, call: 0.25 }, BTN: { tb: 0.09, call: 0.33 } },
    100: { EP: { tb: 0.04, call: 0.16 }, MP: { tb: 0.05, call: 0.20 }, CO: { tb: 0.065, call: 0.26 }, BTN: { tb: 0.085, call: 0.34 } }
  };
  var CARD_DEPTHS = [10, 20, 30, 50, 100];
  var OPENERS = ['EP', 'MP', 'CO', 'BTN'];

  // Blind defense vs an open. BB defends WIDE (closes the action, has a discount);
  // SB leans 3-bet-or-fold (out of position all hand, no closure, no discount).
  // tb = 3-bet (jam ≤20bb); up to call = continue. Includes BB-vs-SB (widest spot).
  var VS_BB = {
    // 10bb calls widened (price-driven): closing HU with ~1bb to call into a
    // ~4.5bb ante pot needs <20% raw equity — folding playable hands is the error
    10: { EP: { tb: 0.05, call: 0.16 }, MP: { tb: 0.06, call: 0.20 }, CO: { tb: 0.08, call: 0.25 }, BTN: { tb: 0.10, call: 0.32 }, SB: { tb: 0.13, call: 0.40 } },
    20: { EP: { tb: 0.05, call: 0.20 }, MP: { tb: 0.06, call: 0.25 }, CO: { tb: 0.08, call: 0.32 }, BTN: { tb: 0.11, call: 0.40 }, SB: { tb: 0.14, call: 0.50 } },
    30: { EP: { tb: 0.04, call: 0.30 }, MP: { tb: 0.05, call: 0.35 }, CO: { tb: 0.07, call: 0.42 }, BTN: { tb: 0.09, call: 0.50 }, SB: { tb: 0.12, call: 0.62 } },
    50: { EP: { tb: 0.04, call: 0.28 }, MP: { tb: 0.05, call: 0.33 }, CO: { tb: 0.07, call: 0.40 }, BTN: { tb: 0.09, call: 0.48 }, SB: { tb: 0.12, call: 0.60 } },
    100: { EP: { tb: 0.035, call: 0.26 }, MP: { tb: 0.045, call: 0.32 }, CO: { tb: 0.065, call: 0.40 }, BTN: { tb: 0.085, call: 0.48 }, SB: { tb: 0.11, call: 0.58 } }
  };
  var VS_SB = {
    10: { EP: { tb: 0.05, call: 0.06 }, MP: { tb: 0.06, call: 0.08 }, CO: { tb: 0.08, call: 0.10 }, BTN: { tb: 0.11, call: 0.14 } },
    20: { EP: { tb: 0.05, call: 0.08 }, MP: { tb: 0.07, call: 0.10 }, CO: { tb: 0.09, call: 0.13 }, BTN: { tb: 0.12, call: 0.17 } },
    30: { EP: { tb: 0.05, call: 0.09 }, MP: { tb: 0.06, call: 0.11 }, CO: { tb: 0.08, call: 0.14 }, BTN: { tb: 0.10, call: 0.18 } }
  };
  function blindVsThresholds(seat, depth, openerPos) {
    var T = seat === 'BB' ? VS_BB : VS_SB;
    var d = T[depth] || T[30];
    return d[openerPos] || d.CO;
  }

  // Multiway SQUEEZE (facing an open + at least one caller): tighter & more value-
  // weighted than a heads-up 3-bet. tb = squeeze (jam ≤20bb), up to call = overcall.
  var SQUEEZE = {
    10: { early: { tb: 0.05, call: 0.06 }, late: { tb: 0.08, call: 0.11 } },
    20: { early: { tb: 0.05, call: 0.07 }, late: { tb: 0.08, call: 0.12 } },
    30: { early: { tb: 0.035, call: 0.09 }, late: { tb: 0.055, call: 0.15 } },
    50: { early: { tb: 0.03, call: 0.10 }, late: { tb: 0.05, call: 0.16 } },
    100: { early: { tb: 0.028, call: 0.11 }, late: { tb: 0.045, call: 0.17 } }
  };
  // Facing a 3-bet after you opened. tb = 4-bet (jam ≤20bb), up to call = flat.
  var VS3BET = {
    20: { ip: { tb: 0.045, call: 0.075 }, oop: { tb: 0.04, call: 0.055 } },
    30: { ip: { tb: 0.030, call: 0.10 }, oop: { tb: 0.028, call: 0.07 } },
    50: { ip: { tb: 0.026, call: 0.14 }, oop: { tb: 0.024, call: 0.09 } },
    100: { ip: { tb: 0.022, call: 0.16 }, oop: { tb: 0.020, call: 0.10 } }
  };
  var POS = ['EP', 'MP', 'CO', 'BTN', 'SB'];
  var POS_NAME = { EP: 'UTG / early', MP: 'MP / lojack', CO: 'cutoff', BTN: 'button', SB: 'small blind' };
  var RORD = 'AKQJT98765432';

  var pctMap = {};    // ALL-IN equity rank: hand -> cumulative combo fraction (0..1)
  var openMap = {};   // OPENING rank (deep default): equity + SC realization residual
  var openMapByDepth = {};
  var defendMap = {}, defendMapByDepth = {};   // DEFEND/flat rank: open rank + set-mine (pairs flat to set-mine — a CALLING consideration, not an opening one)
  // realization depth ramp — how much of the playability residual applies at
  // each depth (grounded: ~half a suited connector's continues are big-pot
  // hands needing stacks; the other half realizes at any depth → floor ~0.45).
  var DEPTH_REAL = { 15: 0.45, 20: 0.65, 30: 0.85, 50: 1.0, 100: 1.0 };
  // Set-mining is the OTHER depth-dependent realization axis (David's small-pair
  // catch): a pocket pair flops a set 11.8%, profitable to flat-and-set-mine an
  // open only when implied odds clear ~15:1 → effective stack ≳ 33bb. So small
  // pairs get a flat/overcall bonus on a STEEP ramp (≈0 short, full deep,
  // crossing ~33-40bb). Smaller pairs lean harder on the set (more bonus);
  // 88+ excluded (they 3-bet, value already in equity). Bypassed at 10bb (Nash).
  var SETMINE = { 22: 0.07, 33: 0.07, 44: 0.06, 55: 0.05, 66: 0.04, 77: 0.03 };
  var PAIR_RAMP = { 15: 0.0, 20: 0.1, 30: 0.45, 50: 0.9, 100: 1.0 };
  // Opening a small pair also realizes (set + initiative + the odd overpair) —
  // modest and less depth-sensitive than flatting. So the OPEN map gives pairs a
  // gentle fraction of the set-mine value on the SC ramp; the DEFEND map gives
  // the full steep set-mine ramp. Net: pairs open WIDER than they flat when
  // short (prefer aggression, low SPR), flat wider than they open when deep.
  var OPEN_PAIR_FRAC = 0.4;
  function nearestRealDepth(d) {
    var ks = [15, 20, 30, 50, 100], best = 100, bd = 1e9;
    for (var i = 0; i < ks.length; i++) { var diff = Math.abs(ks[i] - d); if (diff < bd) { bd = diff; best = ks[i]; } }
    return best;
  }

  function init(data) {
    pctMap = {}; openMap = {};
    if (!data || !data.ranking) return;
    var tot = 0, i;
    for (i = 0; i < data.ranking.length; i++) tot += data.ranking[i].w;
    var cum = 0;
    for (i = 0; i < data.ranking.length; i++) {
      cum += data.ranking[i].w;
      pctMap[data.ranking[i].h] = cum / tot;
    }
    // Realization-adjusted OPENING rank (David's suited-connector catch,
    // 2026-06-12): all-in equity is correct for push/fold but blind to
    // playability — 87s ranked below K2o. openScore = eq + factor(depth)·residual,
    // residual = measured flop-playability beyond what equity predicts (suited
    // connectors flop a continue ~49% vs ~35% for equal-equity offsuit;
    // tools/exp_realization.js). Used for open/iso/defend (postflop pots);
    // push/fold + all-in drills keep pctMap.
    //   DEPTH RAMP (David's stack-size catch): realization value scales with
    //   stack depth — ~half a suited connector's continues are big-pot hands
    //   (straights/flushes/two-pair+) that need stacks to get paid; the other
    //   half (pairs, semi-bluffs) realizes at any depth. So the bonus ramps
    //   from ~0.45 (15bb, low SPR) to 1.0 (50bb+ deep); 10bb opens are pure
    //   Nash jam (realization bypassed entirely). Floor ≈ the depth-neutral
    //   half — never zero while postflop play exists.
    var real = data.realization || {};
    var ranking = data.ranking, totW = tot;
    // openMap: SC realization only (the OPEN decision). defendMap: + set-mine
    // (the FLAT/overcall decision — set-mining is a calling consideration, so it
    // promotes pairs into the call tier without loosening their opens).
    function buildMap(depth, defend) {
      var scF = DEPTH_REAL[depth];
      // pairs: gentle open bonus (SC ramp × frac) vs full steep set-mine flat ramp
      var pairF = defend ? PAIR_RAMP[depth] : OPEN_PAIR_FRAC * DEPTH_REAL[depth];
      var sc = ranking.map(function (r) {
        return { h: r.h, w: r.w, s: r.eq + scF * (real[r.h] || 0) + pairF * (SETMINE[r.h] || 0) };
      });
      sc.sort(function (a, b) { return b.s - a.s; });
      var c = 0, m = {};
      for (var k = 0; k < sc.length; k++) { c += sc[k].w; m[sc[k].h] = c / totW; }
      return m;
    }
    openMapByDepth = {}; defendMapByDepth = {};
    Object.keys(DEPTH_REAL).forEach(function (d) {
      openMapByDepth[d] = buildMap(+d, false);
      defendMapByDepth[d] = buildMap(+d, true);
    });
    openMap = openMapByDepth[100]; defendMap = defendMapByDepth[100];   // deep default
    if (!data.realization) { openMap = pctMap; defendMap = pctMap; openMapByDepth = {}; defendMapByDepth = {}; }
  }
  function pct(label) { return pctMap[label]; }        // undefined if data missing
  function openPct(label, depth) {
    var m = depth != null && openMapByDepth[nearestRealDepth(depth)] ? openMapByDepth[nearestRealDepth(depth)] : openMap;
    return m[label] != null ? m[label] : pctMap[label];
  }
  function defendPct(label, depth) {                    // flat/overcall rank (+ set-mine)
    var m = depth != null && defendMapByDepth[nearestRealDepth(depth)] ? defendMapByDepth[nearestRealDepth(depth)] : defendMap;
    return m[label] != null ? m[label] : pctMap[label];
  }
  function ready() { return Object.keys(pctMap).length > 0; }

  // 'Ah','Ks' -> 'AKs' | 'AKo' | 'AA'  (higher rank first)
  function handLabel(a, b) {
    var r1 = a[0], s1 = a[1], r2 = b[0], s2 = b[1];
    if (RORD.indexOf(r1) > RORD.indexOf(r2)) { var t = r1; r1 = r2; r2 = t; var u = s1; s1 = s2; s2 = u; }
    if (r1 === r2) return r1 + r2;
    return r1 + r2 + (s1 === s2 ? 's' : 'o');
  }

  function jamThreshold(posBucket, stack) {
    var row = JAM[posBucket] || JAM.MP;
    return row[stack] != null ? row[stack] : row[15];
  }
  function callThreshold(jammerBucket, stack) {
    var row = CALL[jammerBucket] || CALL.late;
    return row[stack] != null ? row[stack] : row[15];
  }
  function inRange(label, thresh) {
    var p = pct(label);
    return p != null && p <= thresh;
  }
  function inOpenRange(label, thresh, depth) {          // realization-adjusted (open/iso/defend)
    var p = openPct(label, depth);
    return p != null && p <= thresh;
  }
  function jamCorrect(posBucket, stack, label) { return inRange(label, jamThreshold(posBucket, stack)); }
  function callCorrect(jammerBucket, stack, label) { return inRange(label, callThreshold(jammerBucket, stack)); }

  // Evaluation with a marginal band: {in, marginal, p, t [, ev]}
  function evalAt(thresh, label) {
    var p = pct(label);
    if (p == null) return { in: false, marginal: false, p: 1, t: thresh };
    return { in: p <= thresh, marginal: Math.abs(p - thresh) <= MARGIN, p: p, t: thresh };
  }
  function jamEval(posBucket, stack, label) {
    var Nz = nash();
    if (Nz) {
      var d = nearestDepth(stack), ev = Nz.jam[d] && Nz.jam[d][posBucket] && Nz.jam[d][posBucket][label];
      if (ev != null) return { in: ev > 0, marginal: Math.abs(ev) <= EV_MARGIN, p: pct(label) || 1, t: (Nz.jamPct[d][posBucket] || 0) / 100, ev: ev };
    }
    return evalAt(jamThreshold(posBucket, stack), label);
  }
  function callEval(jammerSeatOrBucket, stack, label) {
    var Nz = nash();
    if (Nz) {
      var d = nearestDepth(stack);
      // prefer the NAMED seat's solved jam range; buckets remain for back-compat
      var seatTbl = Nz.callBBSeat && Nz.callBBSeat[d] && Nz.callBBSeat[d][jammerSeatOrBucket];
      var ev = seatTbl ? seatTbl[label]
        : Nz.callBB[d] && Nz.callBB[d][jammerSeatOrBucket] && Nz.callBB[d][jammerSeatOrBucket][label];
      if (ev != null) {
        var tPct = seatTbl ? (Nz.jamPct[d][jammerSeatOrBucket] || 0) : (Nz.callBBPct[d][jammerSeatOrBucket] || 0);
        return { in: ev > 0, marginal: Math.abs(ev) <= EV_MARGIN, p: pct(label) || 1, t: tPct / 100, ev: ev };
      }
    }
    return evalAt(callThreshold(jammerSeatOrBucket === 'early' || jammerSeatOrBucket === 'late' ? jammerSeatOrBucket : 'late', stack), label);
  }

  // Pocket Card model (depths 10/20/30)
  function openThreshold(pos, depth) { var r = OPEN[depth] || OPEN[20]; return r[pos] != null ? r[pos] : r.CO; }
  function openIn(pos, depth, label) { return inOpenRange(label, openThreshold(pos, depth), depth); }
  function vsAction(depth, openerPos, label) {       // 'threebet' | 'call' | 'fold'
    var row = (VS[depth] || VS[20])[openerPos] || VS[20].CO;
    var p = defendPct(label, depth);
    if (p == null) return 'fold';
    if (p <= row.tb) return 'threebet';
    if (p <= row.call) return 'call';
    return 'fold';
  }
  function vsThresholds(depth, openerPos) { return (VS[depth] || VS[20])[openerPos] || VS[20].CO; }

  // Evals with marginal bands, for the preflop drill.
  function openEval(pos, depth, label) {
    if (depth === 10 && nash()) return jamEval(pos, 10, label);     // 10bb first-in = Nash jam
    var t = openThreshold(pos, depth), p = openPct(label, depth);   // opening: realization rank
    if (p == null) return { in: false, marginal: false, p: 1, t: t };
    return { in: p <= t, marginal: Math.abs(p - t) <= MARGIN, p: p, t: t };
  }
  // useEquity: the nutted-tier wars (vs 4-bet, cold 3-bet) face a polarized
  // strong range where DOMINATION rules — a suited connector's playability
  // can't save it, so those rank by equity. Wide single-raise defends use the
  // realization rank (flatting suited connectors is standard).
  function bandEval(row, label, useEquity, depth) {
    var p = useEquity ? pct(label) : defendPct(label, depth);   // flat tier = defend rank
    if (p == null) return { action: 'fold', p: 1, tb: row.tb, call: row.call, nearTb: false, nearCall: false };
    return {
      action: p <= row.tb ? 'threebet' : p <= row.call ? 'call' : 'fold',
      p: p, tb: row.tb, call: row.call,
      nearTb: Math.abs(p - row.tb) <= MARGIN, nearCall: Math.abs(p - row.call) <= MARGIN
    };
  }
  function vsEval(depth, openerPos, label) { return bandEval(vsThresholds(depth, openerPos), label, false, depth); }
  function blindVsEval(seat, depth, openerPos, label) { return bandEval(blindVsThresholds(seat, depth, openerPos), label, false, depth); }

  // Raise-war adjustments: a strength-ranked prefix misorders 3-bet/4-bet zones.
  // AK plays far ABOVE its raw all-in rank there (blocks AA/KK, dominates the
  // continuing range, wants money in preflop); middle pairs play BELOW theirs
  // (set-mine hands, miserable when 4-bet money goes in). So:
  //   - AKs/AKo are promoted into the aggressive zone at every depth
  //     (≤20bb strictly — flatting a 3-bet with AK at SPR≈1 is a real error;
  //      at 30bb the 4-bet is ideal but flatting is acceptable → marked close)
  //   - TT/99 at 30bb demote from 4-bet to call (still jam ≤20bb)
  var RAISEWAR_PROMOTE = { AKs: 1, AKo: 1 };
  var RAISEWAR_DEMOTE_30 = { TT: 1, 99: 1 };
  // kind: 'war' (vs a 3-bet / cold 3-bet — 4-bet territory) or 'squeeze' (your
  // raise is the FIRST 3-bet). AK promotes in both; the TT/99 demotion applies
  // ONLY in wars — squeezing TT/99 is standard. Overrides carry a `note` so the
  // feedback explains them instead of printing a band the verdict contradicts.
  function raiseWarAdjust(v, depth, label, kind) {
    if (RAISEWAR_PROMOTE[label]) {
      return { action: 'threebet', p: v.p, tb: v.tb, call: v.call, nearTb: depth >= 30, nearCall: false,
        note: 'AK is promoted past its raw rank here — it blocks AA/KK, dominates what continues, and wants the money in preflop.' };
    }
    var war = kind === 'vs3bet' || kind === 'vs4bet' || kind === 'cold3b' || kind === 'war';
    if (war && depth >= 30 && RAISEWAR_DEMOTE_30[label] && v.action === 'threebet') {
      return { action: 'call', p: v.p, tb: v.tb, call: v.call, nearTb: true, nearCall: false,
        note: label + ' ranks inside the raise tier but plays better as a call in 4-bet wars — set-mine value, don’t bloat the pot out of position vs nutted ranges.' };
    }
    if (war && depth >= 50 && RAISEWAR_DEMOTE_DEEP[label] && v.action === 'threebet') {
      var dn = kind === 'cold3b'
        ? label + ' cold vs an open AND a 3-bet: two ranges are already shown (and the opener still acts behind you) — call and play. Cold 4-betting represents exactly AA/KK; vs the tightest wars even folding is fine.'
        : label + ' deep (' + depth + 'bb): calling the 3-bet is the modern default — it keeps their bluffs in and avoids bloating a pot where you’re flipped-or-crushed when the money piles in. 4-betting is fine vs aggressive 3-bettors.';
      return { action: 'call', p: v.p, tb: v.tb, call: v.call, nearTb: true, nearCall: false, note: dn };
    }
    return v;
  }
  var RAISEWAR_DEMOTE_DEEP = { QQ: 1, JJ: 1 };
  // Facing a 4-BET after you 3-bet, 50bb+: the continue range is nutted.
  // tb = 5-bet jam tier (KK+, AK promoted); call = QQ/JJ set-mine-and-evaluate;
  // AQs and worse release.
  var VS4BET = { 50: { tb: 0.013, call: 0.034 }, 100: { tb: 0.011, call: 0.038 } };
  function vs4betEval(depth, posBucket, label) {
    var v = bandEval(VS4BET[depth] || VS4BET[100], label, true);   // nutted tier → equity
    return raiseWarAdjust(v, depth, label, 'vs4bet');
  }
  // Squeeze thresholds depend on WHO you are: BB closes the action with a
  // discount into a multiway pot (pot-odds-driven wide overcall); SB is next
  // best; a field seat has players behind and no discount (tight).
  var SQ_BB_CALL = { 10: 0.30, 20: 0.40, 30: 0.48, 50: 0.46, 100: 0.44 };
  var SQ_SB_CALL = { 10: 0.16, 20: 0.22, 30: 0.28, 50: 0.26, 100: 0.24 };
  function squeezeThresholds(depth, openerBucket, heroSeat, callers) {
    var base = (SQUEEZE[depth] || SQUEEZE[30])[openerBucket] || SQUEEZE[30].late;
    if (heroSeat === 'BB' || heroSeat === 'SB') {
      var tbl = heroSeat === 'BB' ? SQ_BB_CALL : SQ_SB_CALL;
      var call = (tbl[depth] != null ? tbl[depth] : tbl[30]) +
        ((callers || 1) >= 2 ? 0.05 : 0) + (openerBucket === 'early' ? -0.05 : 0);
      return { tb: base.tb, call: Math.max(base.call, call) };
    }
    return base;
  }
  // Hands that play POORLY multiway (domination-prone, one-pair-centric) but
  // dominate the open+call ranges: squeezing to isolate/thin the field is at
  // least as good as overcalling. Suited/connected hands are NOT here — they
  // WANT the multiway pot at a price.
  var SQ_ISOLATE = { AQs: 1, AQo: 1, AJs: 1, KQs: 1, JJ: 1, TT: 1, 99: 1 };
  function squeezeEval(depth, openerBucket, label, heroSeat, callers) {
    var v = bandEval(squeezeThresholds(depth, openerBucket, heroSeat, callers), label, false, depth);
    v = raiseWarAdjust(v, depth, label, 'squeeze');
    if (v.action === 'call' && SQ_ISOLATE[label] && !v.note) {
      return { action: 'threebet', p: v.p, tb: v.tb, call: v.call, nearTb: true, nearCall: false,
        note: label + ' hates the multiway pot it would be overcalling into (one-pair hands get outdrawn in company) but dominates what the opener and caller continue with — squeeze to ISOLATE. Overcalling is acceptable; folding is not.' };
    }
    return v;
  }
  // Facing a 3-bet: the 4-BET tier is a domination war (equity rank — nutted
  // hands + AK), but the FLAT tier is an implied-odds/realization decision. Equity
  // rank wrongly buries the modern flat range — suited connectors, wheel aces,
  // small pairs to set-mine — whose value is flopping well in position, not raw
  // all-in equity. So the flat tier ranks SUITED hands + PAIRS on realization
  // (defendPct), but only IP + DEEP: offsuit hands stay on equity (dominated vs a
  // 3-bet, they don't flop their way out), and OOP / short keep equity too (no
  // realization, no implied odds). Same root cause as the open/defend split
  // (David's suited-ace / SC / small-pair catch, 2026-06-16): a CALL is a
  // realization decision, an all-in is an equity one.
  var VS3BET_FLAT = { 50: 0.14, 100: 0.20 };               // realization-rank flat cap, IP only
  function isSpecHand(label) { return label.length === 2 || label[2] === 's'; }   // pair or suited
  function vs3betEval(depth, posBucket, label) {
    var row = (VS3BET[depth] || VS3BET[30])[posBucket] || VS3BET[30].ip;
    var pw = pct(label);
    if (pw == null) return raiseWarAdjust({ action: 'fold', p: 1, tb: row.tb, call: row.call, nearTb: false, nearCall: false }, depth, label, 'vs3bet');
    if (pw <= row.tb) return raiseWarAdjust({ action: 'threebet', p: pw, tb: row.tb, call: row.call, nearTb: Math.abs(pw - row.tb) <= MARGIN, nearCall: false }, depth, label, 'vs3bet');
    var cap = (posBucket === 'ip' && VS3BET_FLAT[depth] && isSpecHand(label)) ? VS3BET_FLAT[depth] : null;
    var df = cap != null ? defendPct(label, depth) : null;
    var eqCall = pw <= row.call, realCall = df != null && df <= cap;
    if (eqCall || realCall) {
      var viaReal = realCall && !eqCall;
      var v = { action: 'call', p: viaReal ? df : pw, tb: row.tb, call: viaReal ? cap : row.call,
        nearTb: Math.abs(pw - row.tb) <= MARGIN, nearCall: viaReal ? Math.abs(df - cap) <= MARGIN : Math.abs(pw - row.call) <= MARGIN };
      if (viaReal) v.note = label + (label.length === 2 ? ' is a small pair set-mining' : ' is a suited hand that flops well') + ' — facing a 3-bet you 4-bet the nutted hands and FLAT the speculative ones in position with ' + depth + 'bb of implied odds behind. Out of position or short, just fold it.';
      return raiseWarAdjust(v, depth, label, 'vs3bet');
    }
    var fp = df != null ? df : pw, fc = cap != null ? cap : row.call;
    return raiseWarAdjust({ action: 'fold', p: fp, tb: row.tb, call: fc, nearTb: false, nearCall: Math.abs(fp - fc) <= MARGIN }, depth, label, 'vs3bet');
  }
  // Facing a COLD 3-bet (someone opened, someone else 3-bet, action on you):
  // two players have shown strength — continue only with the nutted tier.
  var VSCOLD3B = { 20: { tb: 0.022, call: 0.032 }, 30: { tb: 0.018, call: 0.035 }, 50: { tb: 0.016, call: 0.035 }, 100: { tb: 0.015, call: 0.04 } };
  function cold3bEval(depth, label) {
    return raiseWarAdjust(bandEval(VSCOLD3B[depth] || VSCOLD3B[30], label, true), depth, label, 'cold3b');   // two ranges shown → equity
  }
  function isoThreshold(pos, depth) { return openThreshold(pos, depth) * 0.9; }   // vs a limper, slightly tighter
  function isoEval(pos, depth, label) {
    var t = isoThreshold(pos, depth), p = openPct(label, depth);
    if (p == null) return { in: false, marginal: false, p: 1, t: t };
    return { in: p <= t, marginal: Math.abs(p - t) <= MARGIN, p: p, t: t };
  }

  // SB strategy folded to (heads-up vs BB). With the big-blind ante the SB plays
  // a huge total VPIP (~65-70% deep), split into a RAISE range (openThreshold)
  // and a LIMP/complete range below it — completing cheaply to realize equity
  // OOP. Limp = the playable band (suited/connected + set-mining pairs) by the
  // realization rank; offsuit junk folds. Cutoffs ≈ documented SB-with-ante VPIP,
  // depth-scaled (wide deep, thins short). 10bb = Nash jam, no limp.
  var SB_LIMP = { 20: 0.52, 30: 0.56, 50: 0.62, 100: 0.68 };
  function sbLimpCutoff(depth) { return SB_LIMP[depth] != null ? SB_LIMP[depth] : SB_LIMP[30]; }
  function sbAction(depth, label) {                      // 'raise' | 'limp' | 'fold'
    if (depth <= 10) return openIn('SB', depth, label) ? 'raise' : 'fold';   // jam/fold, no limp
    if (openPct(label, depth) <= openThreshold('SB', depth)) return 'raise';
    if (defendPct(label, depth) <= sbLimpCutoff(depth)) return 'limp';        // complete the playable band
    return 'fold';
  }
  // marginal bands at the raise/limp and limp/fold boundaries
  function sbEval(depth, label) {
    var act = sbAction(depth, label);
    var rt = openThreshold('SB', depth), lc = sbLimpCutoff(depth);
    var op = openPct(label, depth), dp = defendPct(label, depth);
    var nearRaise = op != null && Math.abs(op - rt) <= MARGIN;   // raise↔limp
    var nearLimp = dp != null && Math.abs(dp - lc) <= MARGIN;     // limp↔fold
    return { action: act, nearRaise: nearRaise, nearLimp: nearLimp, raiseT: rt, limpT: lc, op: op, dp: dp };
  }

  // Expand a strength band [lo, hi] (combo-weighted percentiles) into concrete
  // 2-card combos for equity rollouts. Returns array of [card1, card2] strings.
  var SUIT_CH = ['s', 'h', 'd', 'c'];
  function bandCombos(lo, hi) {
    // villain RANGE expansion for postflop equity: hands they actually opened/
    // defended = realization rank (so their range includes the suited
    // connectors they open, not equal-equity offsuit junk they fold)
    var out = [];
    Object.keys(openMap).forEach(function (label) {
      var p = openMap[label];
      if (p <= lo || p > hi) return;
      var r1 = label[0], r2 = label[1], i, j;
      if (label.length === 2) {                          // pair: 6 combos
        for (i = 0; i < 4; i++) for (j = i + 1; j < 4; j++) out.push([r1 + SUIT_CH[i], r2 + SUIT_CH[j]]);
      } else if (label[2] === 's') {                     // suited: 4
        for (i = 0; i < 4; i++) out.push([r1 + SUIT_CH[i], r2 + SUIT_CH[i]]);
      } else {                                           // offsuit: 12
        for (i = 0; i < 4; i++) for (j = 0; j < 4; j++) if (i !== j) out.push([r1 + SUIT_CH[i], r2 + SUIT_CH[j]]);
      }
    });
    return out;
  }

  // count combos in a jam range (for display): sum weights where pct<=thresh
  function rangeCombos(data, thresh) {
    var n = 0;
    for (var i = 0; i < data.ranking.length; i++) {
      if (pctMap[data.ranking[i].h] <= thresh) n += data.ranking[i].w;
    }
    return n;
  }

  var Poker = {
    JAM: JAM, CALL: CALL, STACKS: STACKS, POS: POS, POS_NAME: POS_NAME, RORD: RORD,
    MARGIN: MARGIN, OPEN: OPEN, VS: VS, SQUEEZE: SQUEEZE, VS3BET: VS3BET, CARD_DEPTHS: CARD_DEPTHS, OPENERS: OPENERS,
    init: init, pct: pct, openPct: openPct, defendPct: defendPct, ready: ready, handLabel: handLabel,
    jamThreshold: jamThreshold, callThreshold: callThreshold, inRange: inRange,
    jamCorrect: jamCorrect, callCorrect: callCorrect, rangeCombos: rangeCombos, bandCombos: bandCombos,
    jamEval: jamEval, callEval: callEval,
    openThreshold: openThreshold, openIn: openIn, vsAction: vsAction, vsThresholds: vsThresholds,
    openEval: openEval, vsEval: vsEval, bandEval: bandEval,
    VS_BB: VS_BB, VS_SB: VS_SB, blindVsThresholds: blindVsThresholds, blindVsEval: blindVsEval,
    squeezeEval: squeezeEval, squeezeThresholds: squeezeThresholds, vs3betEval: vs3betEval, isoThreshold: isoThreshold, isoEval: isoEval,
    sbAction: sbAction, sbEval: sbEval, sbLimpCutoff: sbLimpCutoff,
    VSCOLD3B: VSCOLD3B, cold3bEval: cold3bEval, VS4BET: VS4BET, vs4betEval: vs4betEval
  };
  g.Poker = Poker;
  if (typeof module !== 'undefined' && module.exports) module.exports = Poker;
})(typeof window !== 'undefined' ? window : globalThis);
